#!/usr/bin/env bash

FORBIDDEN_BRANCHES=(main dev test)
ALLOWED_BRANCH_PREFIXES=(feature bugfix)
CURRENT_BRANCH=$(git branch | grep '*' | sed 's/* //')
CURRENT_BRANCH_PREFIX=$(git branch | grep '*' | sed 's/* //' | cut -d'/' -f 1)

printf "\e[33;1m%s\e[0m%s\n" 'Current branch: ' $CURRENT_BRANCH

if [[ "${FORBIDDEN_BRANCHES[@]}" =~ "${CURRENT_BRANCH}" ]]; then
  printf "\e[31;1m%s\e[0m\n" "You are trying to commit to \"$CURRENT_BRANCH\" branch directly, which isn't allowed."
  exit 1
fi

if [[ ! "${ALLOWED_BRANCH_PREFIXES[@]}" =~ "${CURRENT_BRANCH_PREFIX}" ]]; then
  printf "\e[31;1m%s\e[0m\n" "You are trying to commit to the branch prefixed with \"$CURRENT_BRANCH_PREFIX\", which isn't allowed."
  printf "\e[32;1m%s\e[0m\n" "Try using one of the following branch prefixes:"
  printf "\e[32;1m%s\e[0m\n" ${ALLOWED_BRANCH_PREFIXES[@]}
  exit 1
fi

printf "\e[33;1m%s\e[0m\n" 'Running the Flutter formatter'
flutter format .
printf "\e[33;1m%s\e[0m\n" 'Finished running the Flutter formatter'
