name: clients_api
description: The interface and models for an API providing access to clients.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3 # A Dart package that helps to implement value based equality without needing to explicitly override == and hashCode.
  json_annotation: ^4.5.0 # Classes and helper functions that support JSON code generation via the `json_serializable` package.
  meta: ^1.7.0 # Annotations used to express developer intentions that can't otherwise be deduced by statically analyzing source code.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  json_serializable: ^6.2.0 # Automatically generate code for converting to and from JSON by annotating Dart classes.
  test: ^1.21.1 # A full featured library for writing and running Dart tests across platforms.
