name: shared_prefs_clients_api
description: An implementation of the ClientsApi that uses NSUserDefaults on iOS and SharedPreferences on Android for local data storage.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  clients_api:
    path: ../clients_api
  decimal: ^2.2.0 # The decimal package allows you to deal with decimal numbers without losing precision.
  meta: ^1.7.0 # Annotations used to express developer intentions that can't otherwise be deduced by statically analyzing source code.
  rxdart: ^0.27.4 # An implementation of the popular reactiveX api for asynchronous programming, leveraging the native Dart Streams api.
  shared_preferences: ^2.0.15 # Flutter plugin for reading and writing simple key-value pairs.
  uuid: ^3.0.6 # RFC4122 (v1, v4, v5) UUID Generator and Parser for all Dart platforms (Web, VM, Flutter)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0 # A Dart mock library which simplifies mocking with null safety support and no manual mocks or code generation.
